# Intelligent Agents: Reflex-Based Agents for the Vacuum-cleaner World

Student Name: [TEAM] Khoa - Phúc - Quý - Tri

I have used the following AI tools: [list tools]

I understand that my submission needs to be my own work: [your initials]

## Learning Outcomes

* Design and build a simulation environment that models sensor inputs, actuator effects, and performance measurement.
* Apply core AI concepts by implementing the agent function for a simple and model-based reflex agents that respond to environmental percepts.
* Practice how the environment and the agent function interact.
* Analyze agent performance through controlled experiments across different environment configurations.
* Graduate Students: Develop strategies for handling uncertainty and imperfect information in autonomous agent systems.

## Instructions

Total Points: 110

Complete this notebook. Use the provided notebook cells and insert additional code and markdown cells as needed. Submit the completely rendered notebook as a HTML file. 

### AI Use

Here are some guidelines that will make it easier for you:

* __Don't:__ Rely on AI auto completion. You will waste a lot of time trying to figure out how the suggested code relates to what we do in class. Turn off AI code completion (e.g., Copilot) in your IDE.
* __Don't:__ Do not submit code/text that you do not understand or have not checked to make sure that it is complete and correct.
* __Do:__ Use AI for debugging and letting it explain code and concepts from class.

### Using Visual Studio Code

Follow [HOWTO Setup the Used Tools] to tuple up your Jupyter Notebook environment.
You can use `Export` (click on `...` in the menu bar) in VS Code to save your notebook as a HTML file. Don't forget to run all blocks before, so the HTML file contains the output of the executed code.

### Using Google Colab

In Colab you need to save the notebook on GoogleDrive to work with it. For this you need to mount your google dive and change to the correct directory. The following code will try to do this if you are on Colab.

In [4]:
# change directory to Google Drive for Google Colab
try:
    from google.colab import drive
    import os

    drive.mount('/content/drive')
    os.chdir('/content/drive/My Drive/Colab Notebooks/')
    print("Your working directory is now Google Drive: My Drive > Colab Notebooks")
except ImportError:
    pass

Once you are done with the assignment and have run all code blocks using `Runtime/Run all`, you can convert your notebook on GoogleDrive into HTML
using: [Convert a Jupyter Notebook to HTML using Colab](https://colab.research.google.com/github/mhahsler/Introduction_to_Artificial_Intelligence/blob/master/HOWTOs/colab_to_html.ipynb).

## Introduction

In this assignment you will implement a simulator environment for an automatic vacuum cleaner robot, a tuple of different reflex-based agent programs, and perform a comparison study for cleaning a single room. Focus on the __cleaning phase__ which starts when the robot is activated and ends when the last dirty square in the room has been cleaned. Someone else will take care of the agent program needed to navigate back to the charging station after the room is clean.

## PEAS description of the cleaning phase

The PEAS description is used in the design phase for an intelligent agent. Make sure your implementations follow this description:

* __Performance Measure:__ Each action costs 1 energy unit. The performance is measured as the sum of the energy units used to clean the whole room.

* __Environment:__ A room with $n \times n$ squares where $n = 5$. Dirt is randomly placed on each square with probability $p = 0.2$. For simplicity, you can assume that the agent knows the size and the layout of the room (i.e., it knows $n$). To start, the agent is placed on a random square.

* __Actuators:__ The agent can clean the current square (action `suck`) or move to an adjacent square by going `north`, `east`, `south`, or `west`.

* __Sensors:__ Four bumper sensors, one for north, east, south, and west; a dirt sensor reporting dirt in the current square.

## The agent program for a simple randomized agent

To show the structure of an agent program, I implement here a simple randomized agent that chooses its actions randomly.

The agent program is implemented as a function that gets sensor information (the current percepts) as the arguments. 
We will use the parameters:

* `bumpers`: A dictionary with boolean entries for the for bumper sensors `north`, `east`, `west`, `south`. E.g., if the agent is on the north-west corner, `bumpers` will be `{"north" : True, "east" : False, "south" : False, "west" : True}`.
* `dirty`: A boolean representing the dirt sensor.

The agent returns the chosen action as a string.

Here is an example implementation for the agent program of a simple randomized agent:

In [5]:
# Google Colab or if you are missing a package: Uncomment the %pip command below, run this block, and restart the session.
# %pip install -q "numpy>=1.26,<3"

In [30]:
import numpy as np

actions = ["north", "east", "west", "south", "suck"]

def simple_randomized_agent(bumpers, dirty):
    return np.random.choice(actions)

In [7]:
# define percepts (current location is NW corner and it is dirty)
bumpers = {"north" : True, "east" : False, "south" : False, "west" : True}
dirty = True

# call agent program function with percepts and it returns an action
simple_randomized_agent(bumpers, dirty)

np.str_('south')

__Note:__ This is not a rational intelligent agent. It ignores its sensors and may bump into a wall repeatedly or not clean a dirty square. You will be asked to implement rational agents below.

## Simple environment example

I show here how to implement a simple simulation environment that supplies the agent program with its percepts and evaluates the agent's actions.
As an example, I implement a room of infinite in size (bumpers are always `False`) where every square is always dirty, even if the agent cleans it. The environment function returns a different performance measure than the one specified in the PEAS description! Since the room is infinite and all squares are constantly dirty, the agent can never clean the whole room. Your implementation needs to implement the **correct performance measure.** The energy budget of the agent is specified as `max_steps`.

In [8]:
def simple_environment(agent_function, max_steps, verbose = True):
    num_cleaned = 0
    
    for i in range(max_steps):
        dirty = True
        bumpers = {"north" : False, "south" : False, "west" : False, "east" : False}

        action = agent_function(bumpers, dirty)
        if (verbose): print("step", i , "- action:", action) 
        
        if (action == "suck"): 
            num_cleaned = num_cleaned + 1
        
    return num_cleaned

Do one simulation run with a simple randomized agent that has enough energy for 20 steps.

In [9]:
simple_environment(simple_randomized_agent, max_steps = 20)

step 0 - action: north
step 1 - action: north
step 2 - action: suck
step 3 - action: west
step 4 - action: north
step 5 - action: north
step 6 - action: east
step 7 - action: south
step 8 - action: west
step 9 - action: suck
step 10 - action: south
step 11 - action: suck
step 12 - action: east
step 13 - action: east
step 14 - action: south
step 15 - action: north
step 16 - action: north
step 17 - action: north
step 18 - action: north
step 19 - action: south

3

# Tasks

## General [10 Points]

1. Make sure that you use the latest version of this notebook. 
2. Your implementation can use libraries like math, numpy, scipy, but not libraries that implement intelligent agents or complete search algorithms. Try to keep the code simple! In this course, we want to learn about the algorithms and we often do not need to use object-oriented design.
3. You notebook needs to be formatted professionally. 
    - Add additional markdown blocks for your description, comments in the code, add tables and use mathplotlib to produce charts where appropriate
    - Do not show debugging output or include an excessive amount of output.
    - Check that your submitted file is readable and contains all figures.
4. Document your code. Use comments in the code and add a discussion of how your implementation works and your design choices.

## Task 1: Implement a simulation environment [20 Points]

The simple environment above is not very realistic. Your environment simulator needs to follow the PEAS description from above. It needs to:

* Initialize the environment by storing the state of each square (clean/dirty) and making some dirty. ([Help with random numbers and arrays in Python])
* Keep track of the agent's position.
* Call the agent function repeatedly and provide the agent function with the sensor inputs.  
* React to the agent's actions. E.g, by removing dirt from a square or moving the agent around unless there is a wall in the way.
* Keep track of the performance measure. That is, track the agent's actions until all dirty squares are clean and count the number of actions it takes the agent to complete the task.

The easiest implementation for the environment is to hold an 2-dimensional array to represent if squares are clean or dirty and to call the agent function in a loop until all squares are clean or a predefined number of steps have been reached (i.e., the robot runs out of energy).

The simulation environment should be a function like the `simple_environment()` and needs to work with the simple randomized agent program from above. **Use the same environment for all your agent implementations in the tasks below.**

*Note on debugging:* Debugging can be difficult. Here are a few options:

* Make sure your environment prints enough information when you use `verbose = True`. 
* VSCode also provides a very good interactive Python debugger for notebooks. Read the [HOWTO on debugging](https://github.com/mhahsler/CS7320-AI/blob/master/HOWTOs/debugging_in_notebooks.ipynb) for more details. 
* Another very useful debugging help is to implement a function that the environment can use to displays the room with dirt and the current position of the robot at every step. You can use simple characters for dirt and the robot location.

In [10]:
import numpy as np
import pprint

In [28]:
import numpy as np


def init_env_square(side_length=5, dirty_probability=0.2):
    """Create a square room and choose a valid random robot position."""
    if side_length <= 0:
        raise ValueError("side_length must be positive")
    if not 0 <= dirty_probability <= 1:
        raise ValueError("dirty_probability must be between 0 and 1")

    grid = np.random.choice(
        [0, 1],
        size=(side_length, side_length),
        p=[1 - dirty_probability, dirty_probability],
    )
    robot_position = tuple(np.random.randint(0, side_length, size=2))
    count_dirty = int(np.sum(grid))

    return grid, robot_position, count_dirty


def detect_bumpers(current_position, side_length=5):
    """Return wall sensors for a robot in a square 2D room."""
    row, column = current_position
    if not (0 <= row < side_length and 0 <= column < side_length):
        raise ValueError("current_position is outside the room")

    return {
        "north": row == 0,
        "east": column == side_length - 1,
        "south": row == side_length - 1,
        "west": column == 0,
    }

Show that your environment works with the simple randomized agent from above.

In [12]:
# Check the bumper
for position in [(0, 0), (0, 4), (4, 0), (4, 4), (2, 2)]:
    print(position, detect_bumpers(position, side_length=5))

(0, 0) {'north': True, 'east': False, 'south': False, 'west': True}
(0, 4) {'north': True, 'east': True, 'south': False, 'west': False}
(4, 0) {'north': False, 'east': False, 'south': True, 'west': True}
(4, 4) {'north': False, 'east': True, 'south': True, 'west': False}
(2, 2) {'north': False, 'east': False, 'south': False, 'west': False}

In [29]:
def square_environment(agent_function, side_length, dirty_probs, max_steps, verbose=True):
    grid, robot_position, initial_dirty_count = init_env_square(
        side_length, dirty_probs
    )
    current_step = 0

    # Stop when every initially dirty square is clean or the energy run out.
    while np.any(grid == 1) and current_step < max_steps:
        row, column = robot_position
        dirty = bool(grid[row, column] == 1)
        bumpers = detect_bumpers(robot_position, side_length)
        action = agent_function(bumpers, dirty)

        if verbose:
            print(
                f"Step {current_step} - Position before action "
                f"{int(row), int(column)} - Action: {action}"
            )

        if action == "suck":
            grid[row, column] = 0
        elif action == "north" and not bumpers["north"]:
            robot_position = (row - 1, column)
        elif action == "south" and not bumpers["south"]:
            robot_position = (row + 1, column)
        elif action == "west" and not bumpers["west"]:
            robot_position = (row, column - 1)
        elif action == "east" and not bumpers["east"]:
            robot_position = (row, column + 1)

        current_step += 1

    remaining_dirty = int(np.sum(grid))
    cleaned_count = initial_dirty_count - remaining_dirty
    return {
        "steps": current_step,
        "initial_dirty": initial_dirty_count,
        "cleaned": cleaned_count,
        "remaining_dirty": remaining_dirty,
        "completed": remaining_dirty == 0,
    }

In [14]:
square_environment(simple_randomized_agent, side_length=5, dirty_probs=0.2, max_steps=21, verbose=True)

Step 0 - Position before action (1, 1) - Action: suck
Step 1 - Position before action (1, 1) - Action: west
Step 2 - Position before action (1, 0) - Action: south
Step 3 - Position before action (2, 0) - Action: east
Step 4 - Position before action (2, 1) - Action: east
Step 5 - Position before action (2, 2) - Action: north
Step 6 - Position before action (1, 2) - Action: north
Step 7 - Position before action (0, 2) - Action: north
Step 8 - Position before action (0, 2) - Action: west
Step 9 - Position before action (0, 1) - Action: suck
Step 10 - Position before action (0, 1) - Action: south
Step 11 - Position before action (1, 1) - Action: east
Step 12 - Position before action (1, 2) - Action: suck
Step 13 - Position before action (1, 2) - Action: north
Step 14 - Position before action (0, 2) - Action: suck
Step 15 - Position before action (0, 2) - Action: suck
Step 16 - Position before action (0, 2) - Action: west
Step 17 - Position before action (0, 1) - Action: west
Step 18 - Position before action (0, 0) - Action: east
Step 19 - Position before action (0, 1) - Action: north
Step 20 - Position before action (0, 1) - Action: south

{'steps': 21,
 'initial_dirty': 2,
 'cleaned': 1,
 'remaining_dirty': 1,
 'completed': False}

## Task 2:  Implement a simple reflex agent [10 Points] 

The simple reflex agent randomly walks around but reacts to the bumper sensor by not bumping into the wall and to dirt with sucking. Implement the agent program as a function.

_Note:_ Agents cannot directly use variable in the environment. They only gets the percepts as the arguments to the agent function. Use the function signature for the `simple_randomized_agent` function above.

In [31]:
# Your code and description goes here
def simple_reflex_agent(bumpers, dirty):
    if dirty: 
        return "suck"

    #  available_action: actions can do (not head the wall)
    available_action = [direction for direction in ["north", "east", "south", "west"] if not bumpers[direction]]

    return np.random.choice(available_action)

Show how the agent works with your environment.

In [16]:
# Your code and description goes here
# call square_environment function but change the simple_randomized_agent to simple_reflex_agent
square_environment(simple_reflex_agent, side_length=5, dirty_probs=0.2, max_steps=21, verbose=True)

Step 0 - Position before action (3, 0) - Action: suck
Step 1 - Position before action (3, 0) - Action: north
Step 2 - Position before action (2, 0) - Action: east
Step 3 - Position before action (2, 1) - Action: south
Step 4 - Position before action (3, 1) - Action: west
Step 5 - Position before action (3, 0) - Action: east
Step 6 - Position before action (3, 1) - Action: north
Step 7 - Position before action (2, 1) - Action: south
Step 8 - Position before action (3, 1) - Action: south
Step 9 - Position before action (4, 1) - Action: suck
Step 10 - Position before action (4, 1) - Action: west
Step 11 - Position before action (4, 0) - Action: north
Step 12 - Position before action (3, 0) - Action: south
Step 13 - Position before action (4, 0) - Action: east
Step 14 - Position before action (4, 1) - Action: west
Step 15 - Position before action (4, 0) - Action: east
Step 16 - Position before action (4, 1) - Action: east
Step 17 - Position before action (4, 2) - Action: west
Step 18 - Position before action (4, 1) - Action: east
Step 19 - Position before action (4, 2) - Action: east
Step 20 - Position before action (4, 3) - Action: east

{'steps': 21,
 'initial_dirty': 5,
 'cleaned': 2,
 'remaining_dirty': 3,
 'completed': False}

## Task 3: Implement a model-based reflex agent [20 Points]

Model-based agents use a state to keep track of what they have done and perceived so far. Your agent needs to find out where it is located and then keep track of its current location. You also need a set of rules based on the state and the percepts to make sure that the agent will clean the whole room. For example, the agent can move to a corner to determine its location and then it can navigate through the whole room and clean dirty squares.

Describe how you define the __agent state__ and how your agent works before implementing it. ([Help with implementing state information in Python])

In [32]:
# Your short description of the state and your implementation goes here

# State save current position, a set of visited cell, current phase, and the next action
def create_model_based_agent(side_length):
    state = {
        "position":[0, 0],
        "visited": set(),
        "phase": "localizing", #  "localizing" | "cleaning" | "finished"
        "next_action": None
    }

    def model_based_agent(bumpers, dirty):
        if dirty:
            return "suck"

        # goto the start position to clean (north-west)
        if state["phase"] == "localizing":
            if not bumpers["north"]:
                return "north"

            if not bumpers["west"]:
                return "west"

            # hit the north & west wall
            state["phase"] = "cleaning"
            state["position"] = [0, 0]
            state["direction"] = "east"

        if state["phase"] == "cleaning":
            if bumpers["east"] == False: # not hit the East wall
                state["position"][1] += 1
                state["visited"].add(tuple(state["position"]))
                state["next_action"] = "east"

                return "east"

            elif (bumpers["east"] == True) and (state["position"][0] != side_length - 1):
                state["position"][0] += 1
                state["visited"].add(tuple(state["position"]))
                state["next_action"] = "south"

                return "south"

            elif bumpers["west"] == False: # not hit the West wall
                state["position"][1] -= 1
                state["visited"].add(tuple(state["position"]))
                state["next_action"] = "west"

                return "west"

            elif (bumpers["west"] == True) and (state["position"][1] == 0):
                state["position"][0] += 1
                state["visited"].add(tuple(state["position"]))
                state["next_action"] = "south"

                return "south"

            elif (
                ((bumpers["east"] == True) and (bumpers["south"] == True)) or 
                ((bumpers["west"] == True) and (bumpers["south"] == True))
            ):
                state["phase"] = "finished" 

        if state["phase"] == "finished":
            return None

    return model_based_agent

In [26]:
# Your code goes here
agent = create_model_based_agent(side_length=5)

Show how the agent works with your environment.

In [27]:
# Your code goes here
square_environment(
    agent,
    side_length=5,
    dirty_probs=0.2,
    max_steps=100
)

Step 0 - Position before action (3, 2) - Action: north
Step 1 - Position before action (2, 2) - Action: north
Step 2 - Position before action (1, 2) - Action: north
Step 3 - Position before action (0, 2) - Action: west
Step 4 - Position before action (0, 1) - Action: west
Step 5 - Position before action (0, 0) - Action: suck
Step 6 - Position before action (0, 0) - Action: east
Step 7 - Position before action (0, 1) - Action: east
Step 8 - Position before action (0, 2) - Action: east
Step 9 - Position before action (0, 3) - Action: east
Step 10 - Position before action (0, 4) - Action: south
Step 11 - Position before action (1, 4) - Action: suck
Step 12 - Position before action (1, 4) - Action: south
Step 13 - Position before action (2, 4) - Action: south
Step 14 - Position before action (3, 4) - Action: south
Step 15 - Position before action (4, 4) - Action: west
Step 16 - Position before action (4, 3) - Action: east
Step 17 - Position before action (4, 4) - Action: west
Step 18 - Position before action (4, 3) - Action: east
Step 19 - Position before action (4, 4) - Action: west
Step 20 - Position before action (4, 3) - Action: east
Step 21 - Position before action (4, 4) - Action: west
Step 22 - Position before action (4, 3) - Action: east
Step 23 - Position before action (4, 4) - Action: west
Step 24 - Position before action (4, 3) - Action: east
Step 25 - Position before action (4, 4) - Action: west
Step 26 - Position before action (4, 3) - Action: east
Step 27 - Position before action (4, 4) - Action: west
Step 28 - Position before action (4, 3) - Action: east
Step 29 - Position before action (4, 4) - Action: west
Step 30 - Position before action (4, 3) - Action: east
Step 31 - Position before action (4, 4) - Action: west
Step 32 - Position before action (4, 3) - Action: east
Step 33 - Position before action (4, 4) - Action: west
Step 34 - Position before action (4, 3) - Action: east
Step 35 - Position before action (4, 4) - Action: west
Step 36 - Position before action (4, 3) - Action: east
Step 37 - Position before action (4, 4) - Action: west
Step 38 - Position before action (4, 3) - Action: east
Step 39 - Position before action (4, 4) - Action: west
Step 40 - Position before action (4, 3) - Action: east
Step 41 - Position before action (4, 4) - Action: west
Step 42 - Position before action (4, 3) - Action: east
Step 43 - Position before action (4, 4) - Action: west
Step 44 - Position before action (4, 3) - Action: east
Step 45 - Position before action (4, 4) - Action: west
Step 46 - Position before action (4, 3) - Action: east
Step 47 - Position before action (4, 4) - Action: west
Step 48 - Position before action (4, 3) - Action: east
Step 49 - Position before action (4, 4) - Action: west
Step 50 - Position before action (4, 3) - Action: east
Step 51 - Position before action (4, 4) - Action: west
Step 52 - Position before action (4, 3) - Action: east
Step 53 - Position before action (4, 4) - Action: west
Step 54 - Position before action (4, 3) - Action: east
Step 55 - Position before action (4, 4) - Action: west
Step 56 - Position before action (4, 3) - Action: east
Step 57 - Position before action (4, 4) - Action: west
Step 58 - Position before action (4, 3) - Action: east
Step 59 - Position before action (4, 4) - Action: west
Step 60 - Position before action (4, 3) - Action: east
Step 61 - Position before action (4, 4) - Action: west
Step 62 - Position before action (4, 3) - Action: east
Step 63 - Position before action (4, 4) - Action: west
Step 64 - Position before action (4, 3) - Action: east
Step 65 - Position before action (4, 4) - Action: west
Step 66 - Position before action (4, 3) - Action: east
Step 67 - Position before action (4, 4) - Action: west
Step 68 - Position before action (4, 3) - Action: east
Step 69 - Position before action (4, 4) - Action: west
Step 70 - Position before action (4, 3) - Action: east
Step 71 - Position before action (4, 4) - Action: west
Step 72 - Position before action (4, 3) - Action: east
Step 73 - Position before action (4, 4) - Action: west
Step 74 - Position before action (4, 3) - Action: east
Step 75 - Position before action (4, 4) - Action: west
Step 76 - Position before action (4, 3) - Action: east
Step 77 - Position before action (4, 4) - Action: west
Step 78 - Position before action (4, 3) - Action: east
Step 79 - Position before action (4, 4) - Action: west
Step 80 - Position before action (4, 3) - Action: east
Step 81 - Position before action (4, 4) - Action: west
Step 82 - Position before action (4, 3) - Action: east
Step 83 - Position before action (4, 4) - Action: west
Step 84 - Position before action (4, 3) - Action: east
Step 85 - Position before action (4, 4) - Action: west
Step 86 - Position before action (4, 3) - Action: east
Step 87 - Position before action (4, 4) - Action: west
Step 88 - Position before action (4, 3) - Action: east
Step 89 - Position before action (4, 4) - Action: west
Step 90 - Position before action (4, 3) - Action: east
Step 91 - Position before action (4, 4) - Action: west
Step 92 - Position before action (4, 3) - Action: east
Step 93 - Position before action (4, 4) - Action: west
Step 94 - Position before action (4, 3) - Action: east
Step 95 - Position before action (4, 4) - Action: west
Step 96 - Position before action (4, 3) - Action: east
Step 97 - Position before action (4, 4) - Action: west
Step 98 - Position before action (4, 3) - Action: east
Step 99 - Position before action (4, 4) - Action: west

{'steps': 100,
 'initial_dirty': 5,
 'cleaned': 2,
 'remaining_dirty': 3,
 'completed': False}

## Task 4: Simulation study [30 Points]

Compare the performance (the performance measure is defined in the PEAS description above) of the agents using  environments of different size. Do at least $5 \times 5$, $10 \times 10$ and
$100 \times 100$. Use 100 random runs for each. Present the results using tables and graphs. Discuss the differences between the agents. 
([Help with charts and tables in Python](https://github.com/mhahsler/CS7320-AI/blob/master/HOWTOs/charts_and_tables.ipynb))

In [33]:
import pandas as pd


def run_simulation_study(room_sizes=(5, 10, 100), runs=100, dirty_probability=0.2):
    """Run 100 independent simulations for each room size and agent."""
    agents = {
        "Randomized Agent": lambda size: simple_randomized_agent,
        "Simple Reflex Agent": lambda size: simple_reflex_agent,
        "Model-based Reflex Agent": create_model_based_agent,
    }
    results = []

    for side_length in room_sizes:
        # 100 steps is enough only for the 5x5 demonstration.
        # Larger rooms need a budget that grows with their area.
        max_steps = max(100, 10 * side_length * side_length)

        for agent_name, agent_factory in agents.items():
            for run_number in range(runs):
                agent_function = agent_factory(side_length)
                result = square_environment(
                    agent_function,
                    side_length=side_length,
                    dirty_probs=dirty_probability,
                    max_steps=max_steps,
                    verbose=False,
                )
                results.append(
                    {
                        "Size": f"{side_length}x{side_length}",
                        "Agent": agent_name,
                        "Run": run_number + 1,
                        "Steps": result["steps"],
                        "Remaining dirty": result["remaining_dirty"],
                        "Completed": result["completed"],
                    }
                )

    return pd.DataFrame(results)


study_results = run_simulation_study()
study_results.head()

  Size             Agent  Run  Steps  Remaining dirty  Completed
0  5x5  Randomized Agent    1    250                3      False
1  5x5  Randomized Agent    2     68                0       True
2  5x5  Randomized Agent    3    146                0       True
3  5x5  Randomized Agent    4    110                0       True
4  5x5  Randomized Agent    5    250                2      False

Fill out the following table with the average performance measure for 100 random runs (you may also create this table with code):

| Size     | Randomized Agent | Simple Reflex Agent | Model-based Reflex Agent |
|----------|------------------|---------------------|--------------------------|
| 5x5     | | | |
| 10x10   | | | |
| 100x100 | | | |

Add charts to compare the performance of the different agents.

In [36]:
summary_table = (
    study_results.groupby(["Size", "Agent"])
    .agg(
        Average_steps=("Steps", "mean"),
        Standard_deviation=("Steps", "std"),
        Completion_rate=("Completed", "mean"),
        Average_remaining_dirty=("Remaining dirty", "mean"),
    )
    .reset_index()
)

summary_table["Completion_rate"] = summary_table["Completion_rate"] * 100

# Table required by the assignment: average performance measure for each agent.
average_steps_table = summary_table.pivot(
    index="Size",
    columns="Agent",
    values="Average_steps",
).reindex(["5x5", "10x10", "100x100"])

average_steps_table

Agent    Model-based Reflex Agent  Randomized Agent  Simple Reflex Agent
Size
5x5                        226.04            222.16               111.33
10x10                     1000.00           1000.00               746.90
100x100                 100000.00         100000.00            100000.00

## Task 5: Robustness of the agent implementations [10 Points] 

Describe how **your agent implementations** will perform 

* if it is put into a rectangular room with unknown size, 
* if the cleaning area can have an irregular shape (e.g., a hallway connecting two rooms), or 
* if the room contains obstacles (i.e., squares that it cannot pass through and trigger the bumper sensors).
* if the dirt sensor is not perfect and gives 10% of the time a wrong reading (clean when it is dirty or dirty when it is clean).
* if the bumper sensor is not perfect and 10% of the time does not report a wall when there is one.

In [ ]:
# Answers goes here

## Advanced task: Imperfect Dirt Sensor

* __Students__ need to complete this task [10 points]

1. Change your simulation environment to run experiments for the following problem: The dirt sensor has a 10% chance of giving the wrong reading. Perform experiments to observe how this changes the performance of the three implementations. Your model-based reflex agent is likely not able to clean the whole room, so you need to measure performance differently as a tradeoff between energy cost and number of uncleaned squares. 

2. Design an implement a solution for your model-based agent that will clean better. Show the improvement with experiments.

In [ ]:
# Your code and discussion goes here

## More Advanced Implementation (not for credit)

If the assignment was to easy for you then you can think about the following problems. These problems are challenging and not part of this assignment. We will learn implementation strategies and algorithms useful for these tasks during the rest of the semester.

* __Obstacles:__ Change your simulation environment to run experiments for the following problem: Add random obstacle squares that also trigger the bumper sensor. The agent does not know where the obstacles are. Perform experiments to observe how this changes the performance of the three implementations. Describe what would need to be done to perform better with obstacles. Add code if you can. 

* __Agent for and environment with obstacles:__ Implement an agent for an environment where the agent does not know how large the environment is (we assume it is rectangular), where it starts or where the obstacles are. An option would be to always move to the closest unchecked/uncleaned square (note that this is actually depth-first search).

* __Utility-based agent:__ Change the environment for a $5 \times 5$ room, so each square has a fixed probability of getting dirty again. For the implementation, we give the environment a 2-dimensional array of probabilities. The utility of a state is defined as the number of currently clean squares in the room. Implement a utility-based agent that maximizes the expected utility over one full charge which lasts for 100000 time steps. To do this, the agent needs to learn the probabilities with which different squares get dirty again. This is very tricky!

In [ ]:
# Your ideas/code